<?php

namespace app\components\modal\selectCity;

use app\components\modal\selectCity\models\City;
use app\components\modal\selectCity\models\District;
use app\components\modal\selectCity\models\Region;
use yii\base\Widget;

class SelectCity extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $regions = Region::find()->with(['districts'])->all();

        // Подготовка данных для передачи в JS
        $data = [];
        foreach ($regions as $region) {
            $districts = [];
            foreach ($region->districts as $district) {
                $cities = [];
                foreach ($district->cities as $city) {
                    $cities[] = [
                        'id' => $city->id,
                        'name' => $city->name,
                    ];
                }
                $districts[] = [
                    'id' => $district->id,
                    'name' => $district->name,
                    'neighborhoods' => array_column($cities, 'name'),
                ];
            }
            $data[$region->id] = [
                'id' => $region->id,
                'name' => $region->name,
                'districts' => $districts,
            ];
        }
        $jsonData = json_encode($data);

        return $this->render("/components/modal/select-city-view", ['regions' => $regions,
                'jsonData' => $jsonData,]
        );
    }

    public function getRegion($id)
    {
        // Находим регион по ID
        $region = Region::findOne($id);
        // Если найдено, возвращаем имя региона, иначе возвращаем строку по умолчанию
        return $region ? $region->name : 'Весь Казахстан';
    }
    public function getDistrict($id)
    {
        // Находим регион по ID
        $district = District::findOne($id);
        // Если найдено, возвращаем имя региона, иначе возвращаем строку по умолчанию
        return $district ? $district->name : 'Все регионы';
    }
    public function getCity($id)
    {
        // Находим регион по ID
        $city = City::findOne($id);
        // Если найдено, возвращаем имя региона, иначе возвращаем строку по умолчанию
        return $city ? $city->name : '';
    }

}
