<?php
return [
    'main-page' => 'Басты бет',
    'city-place' => 'Қала',
    'login' => 'Кіру',
    'register' => 'Тіркелу',
    'email' => 'Эл. пошта',
    'password' => 'Құпия сөз',
    'confirm-pass' => 'Құпия сөзді растаңыз',
    'reg' => 'Тіркелу',
    'close' => 'Жабу',
    'enter' => 'Кіру',
    'info-about-user' => 'Пайдаланушы туралы ақпарат',
    'ext-info' => 'Қосымша ақпарат',
    'was-reg' => 'Тіркелген',
    'last-auth' => 'Соңғы авторизация',
    'role' => 'Рөл',
    'admin-panel' => 'Әкімші панелі',
    'personal-cabinet' => 'Жеке кабинет',
    'exit' => 'Шығу',
    'select-location' => 'Орналасқан жерді таңдаңыз',
    'find-location-placeholder' => 'Тұрғын үй, облыс, қала, ауылды енгізуді бастаңыз',
    'select' => 'Таңдау',
    'dayu' => 'Аламын',
    'beru' => 'Беремiн',
    'work' => 'Жұмыс',
    'welcome' => 'Қош келдіңіз',
    'start-text-select-city' => 'Сайтпен жұмыс істей бастау үшін, қалаңызды таңдаңыз',
    'change-category' => 'Санатты таңдаңыз',
    'all-categories' => 'Барлық санаттар',
    'call-seller' => 'Байланысу',
    'product-image' => 'Өнімнің суреті',
    'info-seller' => 'Ақпарат',
    'change-city-text' => 'Қаланы таңдау',
    'phone-call' => 'Байланыс телефоны',
    'may-like' => 'Сізге де ұнауы мүмкін',
    'social' => 'Әлеуметтік желі',
    'support' => 'Қолдау',
    'free' => 'Тегін',
    'verified' => 'Тексерілген',
    'rejected' => 'Қабылданбады',
    'pending' => 'Тексерілуде',
    'welcomePersonelCabinet'=>'жалғастыру үшін «Мәзір» түймесін басыңыз',

];
